### ISSUE TITLE
SpellLibrary is too awesome! :)

### ISSUE THREAD

**Issue by choekstr** [neptune12100/SpellLibrary#1]
I have been wanting this and while recreating my spells I have had in the past I ran across this and OMG I love it!  What a brilliant piece of work and I used it to pull my spells from my FTB Unstable 1.10 into my Arisen 3 1.9.4 install and it saved me a TON of time. 

Ok, Ok, this isn't an issue but I wanted to provide this feedback for this incredible tool.  VERY well done and kudos for making a great tool.  

Enough gushing now, close this issue and move on.  :)

**Comment by neptune12100** [comment]
Well, wow. Didn't expect people to like this that much. I'm basically doing this to learn .NET. Thanks!
